version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - background_tasks
  background_tasks:
    build:
      context: .
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py process_tasks"