# Generated by Django 2.2.2 on 2019-06-18 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiry', '0002_auto_20190607_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=150)),
                ('check_in_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing_position_number', models.PositiveIntegerField()),
                ('room_category_and_rates', models.CharField(max_length=200)),
                ('ota_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.OTA')),
            ],
        ),
    ]
