# Generated by Django 2.2.3 on 2019-07-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20190622_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='listing_position_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='property_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room_category_and_rates',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('EXECUTING', 'Executing'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
